apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-mnist-gloo"
spec:
  cleanPodPolicy: "None"
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              # image: gcr.io/<your_project>/pytorch_dist_mnist:latest
              image: registry.cn-huhehaote.aliyuncs.com/lumo/pytorch-dist-mnist-test:1.0
              imagePullPolicy: Always
              args: ["--backend", "gloo"]
              # Comment out the below resources to use the CPU.
              resources:
                limits:
                  nvidia.com/gpu: 1
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              # image: gcr.io/<your_project>/pytorch_dist_mnist:latest
              image: registry.cn-huhehaote.aliyuncs.com/lumo/pytorch-dist-mnist-test:1.0
              imagePullPolicy: Always
              args: ["--backend", "gloo"]
              # Comment out the below resources to use the CPU.
              resources:
                limits:
                  nvidia.com/gpu: 1